### ISSUE TITLE
Remove stringly typed check

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/voucher#21]
`isVulnerabilityDiscovery` found here https://github.com/Shopify/voucher/pull/17/files#diff-000ec35b674e1e00d32ecbb98f0dd556R11 should not rely on a string comparison but actually check the type.

**Comment by catherinejones** [comment]
This may not be possible with the state of permissions for the `ContainerAnalysis` API. I will confirm with Google during our sync today.

**Comment by catherinejones** [comment]
As per our contact at Google, we are not able to access this note and should use the note path as the way to determine if it's a vulnerability note!
