### ISSUE TITLE
Readiness check to prevent Voucher from being called when connections are saturated

### ISSUE THREAD

**Issue by catherinejones** [Shopify/voucher#49]
Voucher currently has an issue where it (infrequently) consumes all of the potential network sockets for the system it's running in (usually a Pod in Kubernetes). Our solution to date is to delete the failing Voucher Pod so that Kubernetes starts a new Pod to replace it. This is very inefficient, and it would be preferable to have Kubernetes not send traffic to a pod if its' connections are saturated.

To this end, we should investigate setting up a [readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-readiness-probes) API call, which we can use to prevent Voucher being sent traffic unnecessarily.

This check should measure if it can open new sockets or confirm if it's using too many. If it's close to or at the limit, it should return an error code.

**Comment by chrisdonaldson** [comment]
Why is it consuming all the network sockets?

**Comment by catherinejones** [comment]
I believe it's handling too many connections at once, and they're taking too long to finish. We've attempted to remedy this with https://github.com/Shopify/voucher/pull/37, however we still occasionally have problems and have to restart the Voucher instance.

**Comment by catherinejones** [comment]
Checking a pod that just failed led me to a total of 28431 open sockets! It might be better to find why we have so many open sockets rather than adding this to the health check!

**Comment by catherinejones** [comment]
Based on a quick experiment, it appears that the number of sockets being opened is much smaller and they appear to be closing much more quickly. I'm going to close this issue for now, and we can circle back to it if we want to consider this in the future!
